### ISSUE TITLE
Directory Organization

### ISSUE THREAD

**Issue by haavok** [apreist14/web-iv-portfolio-site#1]
Advanced

I don't see any issues with your organization. It all looks to be labeled descriptively and in the correct folders.

**Comment by e-m-durham** [comment]
ap.svg isn't a very descriptive image name

Consider adding project type into your file name nebraska-game-and-parks-annual-report.html

I wouldn't put the other .css files in the styles > foundation folder, no need to nest a folder in a folder, plus those aren't all necessarily "foundation made" styles, normalize.css is a vendor stylesheet.
