### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by haavok** [apreist14/web-iv-portfolio-site#3]
Satisfactory

Everything is looking good at all screen sizes. There is a weird thing going on with your "next project" and "previous project" buttons on your project page right before it breaks to small screen size. The buttons appear below the photos on the right, but there are images on the left side that fall below the buttons. It would still be functional, just looks a little funky.

**Comment by haavok** [comment]
![Uploading Screen Shot 2015-05-15 at 2.57.46 PM.png…]()
This is a screenshot of what I'm talking about with the buttons.

**Comment by haavok** [comment]
![screen shot 2015-05-15 at 2 57 46 pm](https://cloud.githubusercontent.com/assets/6306010/7660789/e23bce10-fb12-11e4-8d9d-3ea64ec1cb0c.png)

This is a screen cap of the issue with the buttons that I referred to in the last comment.

**Comment by e-m-durham** [comment]
While everything is responsive I think there are areas that could be handled more elegantly for a better user experience. The navigation in small screens, showing an image of your work first on the project page on small screens.  

Also, there are spacing and alignment issues that are emerging in especially the medium screen size.
