### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by haavok** [apreist14/web-iv-portfolio-site#5]
Satisfactory.

There is an extra section element within your portfolio section. I'm not sure if this would be better as a div or not.

Also, watch your header elements. Semantically, they should work like a document outline. Don't just throw in an h6 for smaller headings and h1 for larger ones. Make sure you're using the correct heading element for the content it surrounds.

**Comment by e-m-durham** [comment]
@haavok is right that you need to take a closer look at your heading levels
Marking up subtitles: http://html5doctor.com/howto-subheadings/ or https://css-tricks.com/how-to-mark-up-subtitles/

Your project pages don't have a `<h1>` which is really going to hurt your seo

**Comment by e-m-durham** [comment]
With the `<main>` element, since you are using that on the project page, I'd use it on the home page too for consistency.
