### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by haavok** [apreist14/web-iv-portfolio-site#6]
Proficient

I know you were having some troubles getting the hover overlays to act the right way. That's the only thing I can see that isn't functioning perfectly, and that's only because they don't exactly match up with the images they are overlaying.

**Comment by e-m-durham** [comment]
I think it's going to be important to be able to click on any part of the image/overlay to be able to go to the work. You will want to make sure you get those fully functioning before moving on to styling. I did click on the image at the top and wasn't able to direct to the work page so it read as a pretty critical bug. None of your social icons go anywhere yet.
