### ISSUE TITLE
Cleanliness of Code

### ISSUE THREAD

**Issue by haavok** [apreist14/web-iv-portfolio-site#7]
Below Satisfactory

While your code is well organized and easy to navigate, I noticed that you used special characters several times in your content. Be careful when using apostrophes, quotation marks, and other special punctuation because not all browsers will render them as the symbols that you want. Always use special character codes to ensure that they appear consistently throughout all users' experience.

**Comment by e-m-durham** [comment]
Make sure you are using "smart typography" and special character codes for apostrophes, en dashes, etc.

No need to define larger column widths the same as their smaller column counterpart if they are equal. Foundation is mobile first and will inherit up. For example, line 35 of index.html is `<div class="medium-12 small-12 columns ">` but could be `<div class="small-12 columns ">`

Make sure you have consistent indentation and returns in CSS. Group selectors when it makes sense especially if they have the same properties. Like nav and img in your CSS.
