### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by haavok** [apreist14/web-iv-portfolio-site#8]
Advanced

Your site is very easy to navigate and everything seems to work the way I expected. Everything was easy to find and I always knew where I was and nothing felt out of place. Other than the issue with the buttons on the project page, which I already mentioned, everything is making perfect sense! Awesome!

**Comment by e-m-durham** [comment]
Icons at times are getting pretty small and might be hard to click. How are you going to handle hover states on touch devices?
I see a better mobile navigation experience in your wireframes and I know you were working on that, but your navigation as it stands in this version of your prototype is not helping UX.

**Comment by e-m-durham** [comment]
Consider making your email and phone numbers links.
